name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set identity
        run: git config --global user.email "pickeng2389002@gmail.com" && git config --global user.name "21Jasper12"

      - name: Build project
        run: npm run build --prod --output-path=dist/eco-cv

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ECO_CV_TOKEN }}
          publish_dir: ./dist/eco-cv

      # - name: Prepare and deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ECO_CV_TOKEN }}
      #   run: |
      #     npx angular-cli-ghpages --dir=dist/eco-cv --no-silent
